### ISSUE TITLE
DPI says BUG PLEASE REPORT

### ISSUE THREAD

**Issue by somercet** [GrayHatter/uTox#138]
DPI drop down menu appears, and looks fine, but says "BUG. PLEASE REPORT." and does not work. All the other drop down menus under "User Interface" work.

I was using utox 0.4.4. I will check try to find the error by working backwards in versions, if you like.

System: x86_64
Distro: Arch Testing

utox-git 0.5.0.r41.g708aacc-1 (built in ABS, Arch Build System)

Deps:
desktop-file-utils 0.22-1
fontconfig 2.11.1-2
libfilteraudio-git r92.612c5a1-1
hicolor-icon-theme 0.15-1
libdbus 1.10.6-1
libxext 1.3.3-1
libxrender 0.9.9-1
openal 1.17.1-1
toxcore 3697-1
v4l-utils 1.6.3-3

$ xrandr 
Screen 0: minimum 320 x 200, current 3000 x 1920, maximum 16384 x 16384
DVI-I-1 connected 1920x1080+1080+0 (normal left inverted right x axis y axis) 597mm x 336mm
...
HDMI-1 connected 1080x1920+0+0 left (normal left inverted right x axis y axis) 476mm x 268mm

**Comment by benwaffle** [comment]
what language

**Comment by somercet** [comment]
![2015-12-28-233443_utox_error_scrot](https://cloud.githubusercontent.com/assets/16471479/12029578/4958b2d2-adbc-11e5-8362-5af55596f4e8.png)

This is a screen shot. utox starts in the Light theme, and I can change it to Dark. The text is very, very small, perhaps 5-6 points.

My system runs: "en_US.UTF-8".

**Comment by GrayHatter** [comment]
@somercet you're using nightly builds, they're not supposed to be stable, so yeah. That's expected behaviour. 

The Bug report error is likely because you need to `make clean && make`... If it exists after a `make clean && make` PLEASE let me know. 

About the DPI, I changed the way utox does DPI scaling so that we could have more size options, so by default it starts at the smallest. It should be working normally now that you've changed it back to normal?

**Comment by somercet** [comment]
I did delete the files, took a fresh pull, and the problem persists. I am unable to change the DPI setting at all: the green highlight bar in the DPI drop down does not appear and the DPI settings do not change.

In the drop down menu for DPI, the current setting says "BUG. PLEASE REPORT." and cannot be changed. I cannot "change it back to normal."

**Comment by somercet** [comment]
I also restarted X, and then the desktop. All other apps look fine.

**Comment by GrayHatter** [comment]
run 
`make clean` 
and then `make`
by hand, and past the output here

**Comment by somercet** [comment]
atom utox-git $ make clean
rm -f utox src/*.o src/png/*.o src/icons/*.o src/windows/*.o
atom utox-git $ make
  CC    src/tooltip.o
  CC    src/avatar.o
  CC    src/theme.o
  CC    src/video.o
  CC    src/friend.o
  CC    src/svg.o
  CC    src/main.o
  CC    src/utox_av.o
  CC    src/scrollable.o
  CC    src/dropdown.o
  CC    src/ui.o
src/ui.c: In function ‘draw_user_badge’:
src/ui.c:102:80: warning: pointer targets in passing argument 4 of ‘drawtextrange’ differ in signedness [-Wpointer-sign]
         drawtextrange(SIDEBAR_NAME_LEFT, SIDEBAR_NAME_WIDTH, SIDEBAR_NAME_TOP, "Not connected!", 14);
                                                                                ^
In file included from src/ui.c:1:0:
src/main.h:359:6: note: expected ‘char_t * {aka unsigned char *}’ but argument is of type ‘char *’
 void drawtextrange(int x, int x2, int y, char_t *str, STRING_IDX length);
      ^
  CC    src/dns.o
  CC    src/groups.o
  CC    src/audio.o
  CC    src/util.o
src/util.c: In function ‘file_write_raw’:
src/util.c:52:12: warning: variable ‘outsize’ set but not used [-Wunused-but-set-variable]
     size_t outsize;
            ^
  CC    src/edit.o
  CC    src/ui_dropdown.o
  CC    src/commands.o
  CC    src/ui_i18n.o
  CC    src/button.o
  CC    src/messages.o
src/messages.c: In function ‘messages_draw’:
src/messages.c:244:83: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
             STRING_IDX text_ttc_len = snprintf((char*)text_ttc, sizeof(text_ttc), "%llus", file_ttc);
                                                                                   ^
src/messages.c:244:83: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
  CC    src/tox.o
  CC    src/contextmenu.o
  CC    src/roster.o
  CC    src/text.o
  CC    src/file_transfers.o
  CC    src/png/png.o
  LD    utox

The error recurs. utox displays the string in:

./src/ui_i18n.c:33:static STRING canary = STRING_INIT("BUG. PLEASE REPORT.");

**Comment by GrayHatter** [comment]
are you starting `utox` or `./utox`

**Comment by somercet** [comment]
<pre>./utox</pre>

**Comment by GrayHatter** [comment]
git log -1

**Comment by GrayHatter** [comment]
also, come find me in irc://irc.freenode.net/tox

**Comment by somercet** [comment]
'kay

**Comment by somercet** [comment]
<pre>commit 708aacc22046946804b09da987b0ee940e1f82df
Merge: 530216f 115b5c7
Author: GrayHatter <GrayHatter@users.noreply.github.com>
Date:   Mon Dec 28 18:16:56 2015 -0800

    Merge pull request #123 from doughdemon/develop
    
    Fix binary images on arm
<pre>

**Comment by GrayHatter** [comment]
fixed in 708aacc..5d89cd9
